version: "3.9"
   
services:
  web:
    image: ghcr.io/asilbek99/rekognispa:latest
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: ["bash", "-c", "gunicorn config.wsgi --name=rekognispa --bind=0.0.0.0:8000 --workers=2"]
#    volumes:
#      - ./data/:/usr/share/webapps/rekognispa
    restart: unless-stopped
