version: "3.9"
   
services:
  web:
    image: ghcr.io/Asilbek99/rekognispa
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    command: gunicorn config.wsgi --name=rekognispa --bind=0.0.0.0:8000 --workers=2
    volumes:
      - ./data/:/usr/share/webapps/rekognispa
    restart: unless-stopped
