name: Push

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    timeout-minutes: 30
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.APP_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ca-central-1
      S3_BUCKET_NAME: app-s3-id-43343
      S3_BUCKET_URL: "https://app-s3-id-43343.s3.ca-central-1.amazonaws.com"
      SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      # Setting default tag if none of above was set & Setting full image name>
      - name: Set up Docker buildX
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Prepare tag name from Staging Branch
        run: echo "TAG=master-${GITHUB_SHA::8}-$(date +%s)" >> $GITHUB_ENV

      - name: Set tag and image outputs
        id: set_tag
        run: |
          test -n "${TAG}" || TAG=temp-${GITHUB_SHA::8}-$(date +%s)
          IMAGE="ghcr.io/asilbek99/rekognispa"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      # WRKDR is a Github Actions workaround for WORKDIR in Dockerfiles. See Dockerfile

      - name: Build image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: app/
          file: app/Dockerfile
          push: false
          pull: true
          load: true
          tags: ${{ steps.set_tag.outputs.tagged_image }}
          build-args: |
            SECRET_KEY=${{ secrets.APP_SECRET_KEY }}
            AWS_ACCESS_KEY_ID=${{ secrets.APP_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.APP_AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION=ca-central-1
            S3_BUCKET_NAME=app-s3-id-43343
            S3_BUCKET_URL="https://app-s3-id-43343.s3.ca-central-1.amazonaws.com"

      - name: Push image
        run: docker push ${{ steps.set_tag.outputs.tagged_image }}

      - name: install ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: infrastructure/ansible/
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory host
            --extra-vars image_tag=$TAG 
            --extra-vars docker_username=${{ github.actor }} 
            --extra-vars docker_pass=${{ secrets.GITHUB_TOKEN }}
